/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prop1_hectorsabillon;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Scanner;
/**
 *
 * @author Danny
 */
public class Menu_Labotify extends javax.swing.JFrame {
    
    static Scanner leer = new Scanner(System.in);
    
    ArrayList<Cancion> canciones = new ArrayList<>();
    
    /**
     * Creates new form Menu_Labotify
     */
    public Menu_Labotify() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Labotify");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Listar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Informacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Modificar cancion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3)
                        .addComponent(jButton2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton6)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addGap(47, 47, 47)
                .addComponent(jButton5)
                .addGap(38, 38, 38)
                .addComponent(jButton6)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //boton menu
        Menu menu = new Menu();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //boton agregar
        Cancion cancion = new Cancion();
        
        String input = JOptionPane.showInputDialog(null, "Ingrese el nombre de la cancion");
        cancion.leercancion(input);
        
        String input2 = JOptionPane.showInputDialog(null, "Ingrese el album al que pertenece la cancion");
        cancion.leeralbum(input2);
        
        String input3 = JOptionPane.showInputDialog(null, "Ingrese el artista de la cancion");
        cancion.leerartista(input3);
        
        String input4 = JOptionPane.showInputDialog(null, "Ingrese la fecha de lanzamiento de la cancion");
        int lanzamiento = Integer.parseInt(input4);
        cancion.lanzamiento(lanzamiento);
        
        String input5 = JOptionPane.showInputDialog(null, "Ingrese la duracion de la cancion");
        int duracion = Integer.parseInt(input5);
        cancion.duracion(duracion);
        
        canciones.add(cancion);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //boton listar
        String lista = "";
        
        for (int i = 0; i < canciones.size(); i++){
            lista += Integer.toString(i+1) + ". ";
            lista += canciones.get(i).getName() + "\n";
        }
        JOptionPane.showMessageDialog(null, lista);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //boton eliminar
        String lista = "";
        
        for (int i = 0; i < canciones.size(); i++){
            lista += Integer.toString(i+1) + ". ";
            lista += canciones.get(i).getName() + "\n";
        }
        
        String input = JOptionPane.showInputDialog(null, lista + "\nIngrese el numero de la cancion que desea quitar");
        int opcion = Integer.parseInt(input);
        
        canciones.remove(opcion - 1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //boton informacion
        String lista2 = "";
        
        for (int i = 0; i < canciones.size(); i++){
            lista2 += Integer.toString(i+1) + ". ";
            lista2 += canciones.get(i).getName() + "\n";
        }
        
        String input = JOptionPane.showInputDialog(null, lista2 + "\nIngrese el numero de la cancion");
        int opcion = Integer.parseInt(input);
        String lista = "";
        
        lista += "Nombre: " + canciones.get(opcion-1).getName() + "\n";
        lista += "Album: " + canciones.get(opcion-1).getAlbum() + "\n";
        lista += "Artista: " + canciones.get(opcion-1).getArtist() + "\n";
        lista += "Lanzamiento: " + Integer.toString(canciones.get(opcion-1).getLaunch()) + "\n";
        lista += "Duracion: " + Integer.toString(canciones.get(opcion-1).getDuration());
        
        JOptionPane.showMessageDialog(null, lista);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //boton modificacion
        String lista = "";
        
        for (int i = 0; i < canciones.size(); i++){
            lista += Integer.toString(i+1) + ". ";
            lista += canciones.get(i).getName() + "\n";
        }
        
        String cancion = JOptionPane.showInputDialog(null, lista + "\nIngrese la cancion que desea actualizar");
        int opcion = Integer.parseInt(cancion);
        String input = JOptionPane.showInputDialog(null, "Ingrese el aspecto que desea actualizar de la cancion:\n 1 <- Nombre \n 2 <- Album \n 3 <- Artista \n 4 <- Lanzamiento \n 5 <- Duracion ");
        int opcion2 = Integer.parseInt(input);
        
        switch (opcion2){
            case 1:
                String newname = JOptionPane.showInputDialog(null, "Ingrese el nuevo nombre de la cancion");
                canciones.get(opcion-1).setName(newname);
                break;
            case 2:
                String newalbum = JOptionPane.showInputDialog(null, "Ingrese el nuevo album");
                canciones.get(opcion-1).setAlbum(newalbum);
                break;
            case 3:
                String newartist = JOptionPane.showInputDialog(null, "Ingrese el nuevo artista");
                canciones.get(opcion-1).setArtist(newartist);
                break;
            case 4:
                String newlaunch = JOptionPane.showInputDialog(null, "Ingrese la nueva fecha de lanzamiento");
                int nuevo = Integer.parseInt(newlaunch);
                canciones.get(opcion-1).setLaunch(nuevo);
                break;
            case 5:
                String newduration = JOptionPane.showInputDialog(null, "Ingrese la nueva duracion");
                int nuevo2 = Integer.parseInt(newduration);
                canciones.get(opcion-1).setDuration(nuevo2);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Labotify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
